spring:
  datasource:
    url: jdbc:mysql://47.92.72.146:3306/crm
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,slf4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  messages:
    basename: i18n.login
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    open-in-view: true
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
debug: true
logger:
  level:
    org.springframework.data.jpa: debug

customer:
  security:
    browser:
      signOutUrl: /loginPage?logout
      rememberMeSeconds: 3600*24




